# Generated by Django 5.1 on 2024-09-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposidentificacion',
            name='Otro_campo',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
