# Generated by Django 5.1.1 on 2024-12-25 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBack', '0005_remove_tiposidentificacion_campo_entero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginPersona',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('mail', models.EmailField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Persona Login',
                'verbose_name_plural': 'Personas Login',
                'db_table': 'login_personas',
            },
        ),
    ]
