# Generated by Django 5.0.6 on 2024-05-25 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TiposIdentificacion',
            fields=[
                ('TipoIdentificacionID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('PersonaID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellido', models.CharField(max_length=100)),
                ('Alias', models.CharField(max_length=50)),
                ('NroIdentificacion', models.CharField(max_length=20)),
                ('FechaNacimiento', models.DateField()),
                ('Telefono', models.CharField(max_length=20)),
                ('TipoIdentificacionID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppSGC.tiposidentificacion')),
            ],
        ),
    ]
