# Generated by Django 5.1 on 2024-09-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBack', '0002_tiposidentificacion_otro_campo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposidentificacion',
            name='Otro_campo2',
            field=models.CharField(default='A', max_length=15),
        ),
    ]
