# Generated by Django 5.1 on 2024-09-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBack', '0003_tiposidentificacion_otro_campo2'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposidentificacion',
            name='Campo_entero',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tiposidentificacion',
            name='Campo_entero2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tiposidentificacion',
            name='lcdll',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='tiposidentificacion',
            name='lcdll2',
            field=models.DateTimeField(null=True),
        ),
    ]
