# Generated by Django 5.1 on 2024-10-15 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBack', '0004_tiposidentificacion_campo_entero_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiposidentificacion',
            name='Campo_entero',
        ),
        migrations.RemoveField(
            model_name='tiposidentificacion',
            name='Campo_entero2',
        ),
        migrations.RemoveField(
            model_name='tiposidentificacion',
            name='Otro_campo',
        ),
        migrations.RemoveField(
            model_name='tiposidentificacion',
            name='Otro_campo2',
        ),
        migrations.RemoveField(
            model_name='tiposidentificacion',
            name='lcdll',
        ),
        migrations.RemoveField(
            model_name='tiposidentificacion',
            name='lcdll2',
        ),
        migrations.AddField(
            model_name='tiposidentificacion',
            name='Codigo',
            field=models.CharField(default='Otro', max_length=10),
        ),
        migrations.AlterField(
            model_name='tiposidentificacion',
            name='Descripcion',
            field=models.CharField(max_length=25),
        ),
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellido', models.CharField(max_length=100)),
                ('Alias', models.CharField(max_length=50)),
                ('NroIdentificacion', models.CharField(max_length=20)),
                ('FechaNacimiento', models.DateField()),
                ('Telefono', models.CharField(max_length=20)),
                ('TipoIdentificacionID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppBack.tiposidentificacion')),
                ('UserID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
